### ISSUE TITLE
can i use this

### ISSUE THREAD

**Issue by kernel86-64** [abandonedpools/scaleform#1]
can i use this in mm if i want vac ban

**Comment by abandonedpools** [comment]
It's *possible* to use in MM with a special build of HLAE but it might affect performance and it's not really worth the hassle, I'd instead look into [this project](https://github.com/teamscaleform/scaleform).

**Comment by kernel86-64** [comment]
> It's _possible_ to use in MM with a special build of HLAE but it might affect performance and it's not really worth the hassle, I'd instead look into [this project](https://github.com/teamscaleform/scaleform).

wait,where do i get hlae without -insecure? (i tried googling it, didn't find anything though) (i'm asking because teamscaleform didn't compile)
sorry if i'm annoying you

**Comment by abandonedpools** [comment]
I think teamscaleform has the compiled dll's in their server (if not you can still probably just ask someone for it in there). As for HLAE they don't have non-insecure versions up anymore (because people used them for stuff like this) so you have to modify and compile the source yourself, which I have no experience doing so I can't help much.
